language: go

go:
  - "1.12"
  - "1.13"
  - "1.14"
  - "master"

arch:
  - amd64

os:
  - linux
  - osx
  - windows

matrix:
  include:
    - os: linux
      arch: amd64
      go: "1.14"
    - os: linux
      arch: arm64
      go: "1.14"
    - os: linux
      arch: ppc64le
      go: "1.14"
  allow_failures:
    - go: "master"
  fast_finish: true

script:
  - go test -v -tags=test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
