language: go

go:
  - 1.x
  - "1.14"
  - master

arch:
  - amd64

os:
  - linux
  - osx
  - windows

dist: bionic

env:
  - GO111MODULE=on

before_install:
  - go get github.com/mattn/goveralls

script:
  # https://github.com/mattn/goveralls
  - goveralls -flags="-x" -v -race -covermode=atomic -service=travis-ci -package=./

after_script:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks: https://coveralls.io/webhook

jobs:
  include:
    - os: linux
      arch: arm64
      go: "1.14"
    - os: linux
      arch: ppc64le
      go: "1.14"
    - os: linux
      arch: s390x
      go: "1.14"
      script:
        # Go's race detector does not work on s390x
        - goveralls -flags="-x" -v -covermode=atomic -service=travis-ci -package=./

  allow_failures:
    - go: "master"

  fast_finish: true
